[package]
name = "template-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
const_format = "*"
mimalloc = "*"
regex = "*"

[build-dependencies]
winresource = "*"

[profile.release]
# opt-level = "z" # Uncomment to enable zero optimization (slower but smaller binary)
opt-level = 3
strip = true
lto = true
panic = "abort"
codegen-units = 1
